/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TaskTwoLazyImport = createFileRoute('/task-two')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TaskTwoLazyRoute = TaskTwoLazyImport.update({
  path: '/task-two',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/task-two.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/task-two': {
      id: '/task-two'
      path: '/task-two'
      fullPath: '/task-two'
      preLoaderRoute: typeof TaskTwoLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/task-two': typeof TaskTwoLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/task-two': typeof TaskTwoLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/task-two': typeof TaskTwoLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/task-two'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/task-two'
  id: '__root__' | '/' | '/task-two'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TaskTwoLazyRoute: typeof TaskTwoLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TaskTwoLazyRoute: TaskTwoLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/task-two"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/task-two": {
      "filePath": "task-two.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
